body:
- attributes:
    label: Device you want to apply for
    description: 'Example: POCO F1 (beryllium)'
  type: input
  validations:
    required: true
- attributes:
    description: One URL per line
    label: Device Tree Sources
  type: textarea
  validations:
    required: true
- attributes:
    label: Number of ROM's you maintain officially/unofficially, also name them
  type: input
  validations:
    required: true
- attributes:
    label: Any Exceptions/special concern?
  type: textarea
  validations:
    required: true
- attributes:
    label: Telegram username
  type: input
  validations:
    required: true
- attributes:
    label: GitHub username
  type: input
  validations:
    required: true
name: Maintainership Form
description: Application for applying as maintainer
title: New maintainer
assignees: [tejas101k, athizz2005, Subratam6296, ashutoshchettri, abhishekpeddada]
